# Generated by Django 5.0.2 on 2024-03-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tenant",
            field=models.CharField(default="public", max_length=20),
        ),
    ]
