# Generated by Django 5.0.2 on 2024-03-13 19:26

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("no_of_available_invoice_users", models.IntegerField()),
                ("no_of_available_admin_users", models.IntegerField()),
                ("paid_until", models.DateField()),
                ("on_trial", models.BooleanField()),
                ("bank_name", models.CharField(max_length=100)),
                ("bank_account_name", models.CharField(max_length=100)),
                ("bank_account_no", models.IntegerField()),
                ("bank_sort_code", models.CharField(max_length=100)),
                ("invoice_footer", models.TextField()),
                ("created_on", models.DateField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="organisation.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
