# Generated by Django 5.0.2 on 2024-03-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="no_of_available_users",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
