# Generated by Django 5.0.2 on 2024-03-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
