# Generated by Django 5.0.2 on 2024-03-12 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0002_client_no_of_available_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="no_of_available_users",
            new_name="no_of_available_invoice_users",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="no_of_users",
            new_name="no_of_available_normal_users",
        ),
    ]
