# Generated by Django 5.0.2 on 2024-03-12 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "organisation",
            "0003_rename_no_of_available_users_client_no_of_available_invoice_users_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="no_of_available_normal_users",
            new_name="no_of_available_admin_users",
        ),
    ]
