# Generated by Django 5.0.2 on 2024-05-05 20:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(null=True)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('date_joined', models.DateField()),
                ('date_left', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('client_type', models.CharField(choices=[('private_funded', 'Private Funded'), ('authorities_funded', 'Authorities Funded')], default='private_funded', max_length=20)),
                ('rates', models.JSONField(default=dict)),
                ('resident_name_number', models.CharField(max_length=255)),
                ('respite', models.BooleanField(null=True)),
                ('notes', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalAuthority',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('hide_client_deatils', models.BooleanField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OneToOneAgency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('present', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.client')),
            ],
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='contracts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.client')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_number', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('costs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.IntegerField(default=1)),
                ('settled', models.BooleanField(default=False)),
                ('sent_to_client', models.BooleanField(default=False)),
                ('additional_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.client')),
            ],
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('invoice_to_allocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='payable_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.localauthority'),
        ),
        migrations.CreateModel(
            name='MoneyIn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_left', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('desc', models.CharField(default='', max_length=255)),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('invoices_to_allocate', models.ManyToManyField(blank=True, related_name='monies_in', to='backend.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='OneToOne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.client')),
            ],
        ),
    ]
