# Generated by Django 5.0.2 on 2024-05-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('authorities_funded', 'Authorities Funded'), ('private_funded', 'Private Funded')], default='private_funded', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='resident_name_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
