# Generated by Django 5.0.2 on 2024-05-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_client_client_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('private_funded', 'Private Funded'), ('authorities_funded', 'Authorities Funded')], default='private_funded', max_length=20),
        ),
    ]
