# Generated by Django 5.0.2 on 2024-05-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_client_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('authorities_funded', 'Authorities Funded'), ('private_funded', 'Private Funded')], default='private_funded', max_length=20),
        ),
    ]
