# Generated by Django 5.0.2 on 2024-05-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_client_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rates',
            field=models.JSONField(),
        ),
    ]
