# Generated by Django 5.0.2 on 2024-06-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_client_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('private_funded', 'Private Funded'), ('authorities_funded', 'Authorities Funded')], default='private_funded', max_length=20),
        ),
    ]
