# Generated by Django 5.0.2 on 2024-03-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0006_alter_client_client_types_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_types",
            field=models.CharField(
                choices=[
                    ("authorities_funded", "Authorities Funded"),
                    ("private_funded", "Private Funded"),
                ],
                default="private_funded",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="client_types",
            field=models.CharField(
                choices=[
                    ("authorities_funded", "Authorities Funded"),
                    ("private_funded", "Private Funded"),
                ],
                default="private_funded",
                max_length=20,
            ),
        ),
    ]
