"""
Django settings for wip project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from django.db import connection
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-&b7-v(siu&f4nb-(81@fm*pbu5n1eg(&ecf^x5)+ixht7yvu+o"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

SHARED_APPS = [
    'django_tenants',  # mandatory
    "organisation",
    "django.contrib.admin",
    "users",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    'bootstrap4',
    'fontawesomefree',
    'simple_history',
    'django_cron',
    'django_crontab',
    'preventconcurrentlogins',
]

TENANT_APPS = [
    'backend',
    "frontend",
]

INSTALLED_APPS = [app for app in TENANT_APPS if app not in SHARED_APPS] + list(SHARED_APPS)

TENANT_MODEL = "organisation.Client" # app.Model

TENANT_DOMAIN_MODEL = "organisation.Domain"  # app.Model

AUTH_USER_MODEL = 'users.CustomUser'

MIDDLEWARE = [

    'django_tenants.middleware.main.TenantMainMiddleware',
    'wip.middleware.CheckPaidPeriodMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    'wip.middleware.ValidTenantUserMiddleware',
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'simple_history.middleware.HistoryRequestMiddleware',
    'preventconcurrentlogins.middleware.PreventConcurrentLoginsMiddleware',
    
]

ROOT_URLCONF = "wip.urls"

WEASYPRINT_BASEURL = '/'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wip.wsgi.application"
LOGIN_URL = '/user/login/'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

DATABASES = {
    "default": {
        "ENGINE": "django_tenants.postgresql_backend",
        "NAME": "invoicing",
        'USER': 'gb',
        'PASSWORD': 'Mango@ANP290!',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-uk"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

USE_TZ = True
SHORT_DATE_FORMAT = 'd/m/Y'


EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp-mail.outlook.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'gursimran_bassi@outlook.com'
EMAIL_HOST_PASSWORD = 'Bassihome1906'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



CRONJOBS = [
    ('0 15 * * *', 'backend.cron.daily_check_for_unmarked_attendance')
]

CRON_CLASSES = [
    'backend.cron.DailyCheckForUnmarkedAttendance', 
]